### ISSUE TITLE
Registering a User (business / profile) 

### ISSUE THREAD

**Issue by AlexandraNicolau** [SchoolOfCode/final-project-server-eco-warriors#2]
-[ ] depending if a business or personal user 
  - [x] if you choose business user you are given a form with the following fields (all required): 
    - [ ] Business Name
    - [ ] Business Email
    - [ ] Business Password
    - [ ] Business Address
    - [ ] Business Postcode
    - [ ] Business City 
    - [ ] Business Description 
    - [ ] Business Sector / Categories (Reduce Plastic, Personal Care, Reduce Meat, Zero Waste shops) 

  - [x] if you choose personal user you are given a form with the following fields (all required):   
    - [ ] First Name
    - [ ] Surname 
    - [ ] Email
    - [ ] Password
    - [ ] Location / City
  
- [ ] does firebase send an authentication email?
- [x] can we login the user directly after submitting registration form?
  - [ ] if yes, they should be redirected to Interests page 
  - [ ] if no, they should be redirected to the login page 
- [ ] include form validation?
