### ISSUE TITLE
Interests Page 

### ISSUE THREAD

**Issue by AlexandraNicolau** [SchoolOfCode/final-project-server-eco-warriors#3]
- [ ] set up a Firebase database with 2 collections: Persons and Businesses (yep, they are actually called collections in Firebase too, how cool!) 

  - [ ] Persons collection will contain:
   - [ ] unique ID
   - [ ] first name
   - [ ] last name
   - [ ] email
   - [ ] password
   - [ ] interests (list) 
   - [ ] transactions 
      - [ ] unique id
      - [ ] time stamp (UTC) 
      - [ ] value of transaction 
      - [ ] shop ID
      - [ ] points (maybe?) 

  - [ ] Businesses collection will contain:
   - [ ] unique ID
   - [ ] business description 
   - [ ] name of business
   - [ ] email
   - [ ] password
   - [ ] address
   - [ ] postcode
   - [ ] city
   - [ ] business category (type)
